apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: shopware-mysql
  namespace: shopware
  labels:
    fmj.dev/component: shopware-mysql
spec:
  crVersion: 1.16.0
  secretsName: shopware-pxc-credentials
  unsafeFlags:
    tls: true
    pxcSize: true
    proxySize: true
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  tls:
    enabled: false
  pxc:
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 4Gi
    # https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks.html
    configuration: |
      [mysqld]
      # Performance configurations
      back_log = 50
      max_connections = 100
      wait_timeout = 256
      max_connect_errors = 10

      table_open_cache = 2048
      max_allowed_packet = 64M
      max_heap_table_size = 512M

      read_buffer_size = 64M
      read_rnd_buffer_size = 64M
      sort_buffer_size = 64M
      join_buffer_size = 64M

      thread_cache_size = 8
      thread_stack = 240K

      ft_min_word_len = 4
      transaction_isolation = REPEATABLE-READ
      tmp_table_size = 512M

      slow_query_log
      long_query_time = 2
      server-id = 1

      # Shopware configuration
      default-time-zone = '+00:00'
      group_concat_max_len = 400000
      sql-mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'

  users:
    - name: shopware
      dbs:
        - shopware
      hosts:
        - localhost
        - 10.244.0.0/16 # Pod CIDR
      grants:
        - ALL
      #        - SELECT
      #        - DELETE
      #        - INSERT
      #        - CREATE
      passwordSecretRef:
        name: shopware-mysql-credentials
        key: password

    #  secretsName: shopware-db-credentials
    #  crVersion: 1.14.1
    #  allowUnsafeConfigurations: true
    #  initImage: "percona/percona-xtradb-cluster-operator:1.14.1"
    #  pxc:
    #    size: 1
    #    image: percona/percona-xtradb-cluster:8.4
    #    autoRecovery: true
    #    volumeSpec:
    #      persistentVolumeClaim:
    #        storageClassName: standard
    #        resources:
    #          requests:
    #            storage: 4Gi
    #    gracePeriod: 600
  haproxy:
    enabled: true
    size: 1
    image: percona/haproxy:2.8.11

  proxysql:
    enabled: false
    image: perconalab/percona-xtradb-cluster-operator:main-proxysql
    size: 1
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
#    configuration: |
#      datadir="/var/lib/proxysql"
#
#      admin_variables =
#      {
#        admin_credentials="proxyadmin:proxyadmin"
#        mysql_ifaces="0.0.0.0:6032"
#        refresh_interval=2000
#
#        cluster_username="proxyadmin"
#        cluster_password="proxyadmin"
#        cluster_check_interval_ms=200
#        cluster_check_status_frequency=100
#        cluster_mysql_query_rules_save_to_disk=true
#        cluster_mysql_servers_save_to_disk=true
#        cluster_mysql_users_save_to_disk=true
#        cluster_proxysql_servers_save_to_disk=true
#        cluster_mysql_query_rules_diffs_before_sync=1
#        cluster_mysql_servers_diffs_before_sync=1
#        cluster_mysql_users_diffs_before_sync=1
#        cluster_proxysql_servers_diffs_before_sync=1
#      }
#
#      mysql_variables=
#      {
#        monitor_password="monitor"
#        monitor_galera_healthcheck_interval=1000
#        threads=2
#        max_connections=2048
#        default_query_delay=0
#        default_query_timeout=10000
#        poll_timeout=2000
#        interfaces="0.0.0.0:3306"
#        default_schema="information_schema"
#        stacksize=1048576
#        connect_timeout_server=10000
#        monitor_history=60000
#        monitor_connect_interval=20000
#        monitor_ping_interval=10000
#        ping_timeout_server=200
#        commands_stats=true
#        sessions_sort=true
#        have_ssl=false
#      }
