# ref: https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: redacted
  namespace: redacted
spec:
  nodePools:
    - component: masters
      pdb:
        enable: true
        minAvailable: 1
      replicas: 3
      diskSize: 2Gi
      nodeSelector:
      resources:
        requests:
          memory: 500Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
      roles:
        - cluster_manager
        - data
    - component: nodes
      replicas: 3
      diskSize: 5Gi
      nodeSelector:
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1000m
      roles:
        - data
      persistence:
        pvc:
          storageClass: standard
          accessModes:
            - ReadWriteOnce
    - component: coordinators
      replicas: 3
      diskSize: 2Gi
      nodeSelector:
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1000m
      roles:
        - ingest
