apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: ca-development-issuer
    target:
      name: shopware
      kind: Ingress
      labelSelector: "app.kubernetes.io/component=shop"
