# config/packages/framework.yaml
framework:
  # caching
  cache:
    default_redis_provider: "%env(string:REDIS_URL)%"
    pools:
      cache.http:
        adapter: cache.adapter.redis_tag_aware
        tags: cache.tags

  # shortcut for private IP address ranges of your proxy
  trusted_proxies: "private_ranges"
  # trust *all* "X-Forwarded-*" headers
  trusted_headers:
    [
      "x-forwarded-for",
      "x-forwarded-host",
      "x-forwarded-proto",
      "x-forwarded-port",
      "x-forwarded-prefix",
    ]
