# config/packages/framework.yaml
framework:
  # use Redis for HTTP caching
  # ref: https://developer.shopware.com/docs/guides/hosting/performance/caches.html#example-replace-some-cache-with-redis
  cache:
    default_redis_provider: "%env(string:REDIS_URL)%"
    pools:
      cache.http:
        adapter: cache.adapter.redis_tag_aware
        tags: cache.tags

  # shortcut for private IP address ranges of your proxy
  trusted_proxies: "private_ranges"
  # trust *all* "X-Forwarded-*" headers
  trusted_headers:
    [
      "x-forwarded-for",
      "x-forwarded-host",
      "x-forwarded-proto",
      "x-forwarded-port",
      "x-forwarded-prefix",
    ]

  # ref: https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks.html#disable-symfony-secrets
  secrets:
    enabled: false
