# config/packages/framework.yaml
framework:
  # shortcut for private IP address ranges of your proxy
  trusted_proxies: 'private_ranges'
  # trust *all* "X-Forwarded-*" headers
  trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]