# required to build Shopware without a connection to the (production) database
#
# NOTE: Shopware still throws MySQL and Redis connection errors, but catches and deals with them. Therefore they
#       can be safely ignored.
# ref: https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/build-w-o-db.html
storefront:
  theme:
    config_loader_id: Shopware\Storefront\Theme\ConfigLoader\StaticFileConfigLoader
    available_theme_provider: Shopware\Storefront\Theme\ConfigLoader\StaticFileAvailableThemeProvider
    theme_path_builder_id: Shopware\Storefront\Theme\MD5ThemePathBuilder
