services:
  traefik:
    image: traefik:v3.0.4
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public
    labels:
      - "application=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.tls.domains[0].main=traefik.shopware.private"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.traefik.shopware.private"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.shopware.private`)"
    configs:
      - source: traefik.yml
        target: /etc/traefik/traefik.yml
      - source: traefik-dynamic.yml
        target: /etc/traefik/traefik-dynamic.yml
    secrets:
      - source: server.pem
        target: /etc/ssl/traefik/server.pem
      - source: server-key.pem
        target: /etc/ssl/traefik/server-key.pem
    security_opt:
      - no-new-privileges:true

  shopware:
    image: fmjstudios/shopware:latest
    container_name: shopware
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    restart: always
    ports:
      - "9161"
    volumes:
      - ./custom/plugins:/var/www/html/custom/plugins:ro
      - ./custom/apps:/var/www/html/custom/apps:ro
      - sw-files:/var/www/html/files:rw
      - sw-theme:/var/www/html/public/theme:rw
      - sw-media:/var/www/html/public/media:rw
      - sw-thumbnail:/var/www/html/public/thumbnail:rw
      - sw-sitemap:/var/www/html/public/sitemap:rw
    networks:
      - public
      - internal
    labels:
      - "application=shopware"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.shopware.entrypoints=https"
      - "traefik.http.routers.shopware.tls=true"
      - "traefik.http.routers.shopware.tls.domains[0].main=shopware.private"
      #- "traefik.http.routers.shopware.tls.domains[0].sans=*.shopware.private"
      - "traefik.http.routers.shopware.rule=Host(`shopware.private`)"
      - "traefik.http.routers.shopware.service=shopware"
      - "traefik.http.services.shopware.loadbalancer.server.port=9161"
      - "traefik.http.services.shopware.loadbalancer.sticky=true"
      - "traefik.http.services.shopware.loadbalancer.sticky.cookie=true"
    depends_on:
      traefik:
        condition: service_started
      mysql:
        condition: service_started
      opensearch:
        condition: service_started
      mailpit:
        condition: service_started

  mysql:
    image: mysql:${MYSQL_VERSION:-8}-oracle
    container_name: mysql
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shopware}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-shopware}
      MYSQL_USER: ${MYSQL_USER:-shopware}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-shopware}
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - internal
    labels:
      - "application=mysql"
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-shopware}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  # ref: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    ports:
      - "9200" # REST API
      - "9600" # Performance Analyzer
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "AShopware6Password!"
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - internal
    labels:
      - "application=opensearch"
      - "traefik.enable=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  # ref: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    ports:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      opensearch.username: shopware
      opensearch.password: shopware
    networks:
      - public
      - internal
    labels:
      - "application=opensearch-dashboards"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.opensearch.entrypoints=https"
      - "traefik.http.routers.opensearch.tls=true"
      - "traefik.http.routers.opensearch.tls.domains[0].main=opensearch.shopware.private"
      - "traefik.http.routers.opensearch.tls.domains[0].sans=*.opensearch.shopware.private"
      - "traefik.http.routers.opensearch.rule=Host(`opensearch.shopware.private`)"
      - "traefik.http.routers.opensearch.service=opensearch"
      - "traefik.http.services.opensearch.loadbalancer.server.port=5601"

  # ref: https://mailpit.axllent.org/docs/configuration/runtime-options/
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - public
    labels:
      - "application=mailpit"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.mailpit.entrypoints=https"
      - "traefik.http.routers.mailpit.tls=true"
      - "traefik.http.routers.mailpit.tls.domains[0].main=mailpit.shopware.private"
      - "traefik.http.routers.mailpit.tls.domains[0].sans=*.mailpit.shopware.private"
      - "traefik.http.routers.mailpit.rule=Host(`mailpit.shopware.private`)"
      - "traefik.http.routers.mailpit.service=mailpit"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"

configs:
  traefik.yml:
    file: docker/resources/traefik.yml
  traefik-dynamic.yml:
    file: docker/resources/traefik-dynamic.yml

secrets:
  server.pem:
    file: secrets/ssl/server.pem
  server-key.pem:
    file: secrets/ssl/server-key.pem

volumes:
  sw-files:
  sw-theme:
  sw-media:
  sw-thumbnail:
  sw-sitemap:
  db-data:
  opensearch-data:

networks:
  public:
    external: true
  internal: