
services:
  shopware:
    image: fmjstudios/shopware:latest
    # user: "1001:1001"
    labels:
      app: shopware
    build:
      context: ..
      dockerfile: Dockerfile
    env_file: ../.env
    ports:
      - "80:8080"
    environment:
      # APP_URL: "http://shopware.private"
      PHP_DISPLAY_ERRORS: On
      PHP_ERROR_REPORTING: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
      # PHP_FPM_ERROR_LOG: /var/log/php-fpm/error.log
      # PHP_FPM_ACCESS_LOG: /var/log/php-fpm/access.log
    volumes:
      - sw-files:/var/www/html/files:rw
      - sw-theme:/var/www/html/public/theme:rw
      - sw-media:/var/www/html/public/media:rw
      - sw-thumbnail:/var/www/html/public/thumbnail:rw
      - sw-sitemap:/var/www/html/public/sitemap:rw
    networks:
      - web
      - internal
    depends_on:
      mysql:
        condition: service_started
      opensearch:
        condition: service_started
      mailpit:
        condition: service_started

  mysql:
    image: mysql:${MYSQL_VERSION:-8}-oracle
    labels:
      app: mysql
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shopware}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-shopware}
      MYSQL_USER: ${MYSQL_USER:-shopware}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-shopware}
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-uroot", "-pshopware"]
      interval: 5s
      timeout: 5s
      retries: 20

  opensearch:
    image: opensearchproject/opensearch:2
    labels:
      app: opensearch
    ports:
      - "9200"
      - "9600"
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: AShopware6Password!
      discovery.type: single-node
      plugins.security.disabled: true
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - internal

  mailpit:
    image: axllent/mailpit
    labels:
      app: mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - internal

volumes:
  sw-files:
  sw-theme:
  sw-media:
  sw-thumbnail:
  sw-sitemap:
  db-data:
  opensearch-data:


networks:
  web:
  internal: