apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
    target:
      name: shopware
      kind: Ingress
      labelSelector: "app.kubernetes.io/component=shop"
  - path: configmap-patch.yaml
    target:
      name: shopware-config
      kind: ConfigMap
      labelSelector: "app.kubernetes.io/component=shop"
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: linode-block-storage-retain
    target:
      name: shopware-docroot
      kind: PersistentVolumeClaim
      labelSelector: "app.kubernetes.io/component=shop"