---
releases:
  # ref: https://artifacthub.io/packages/helm/bitnami/redis
  - chart: bitnami/redis
    name: shopware-redis
    labels:
      release: shopware
    namespace: shopware
    version: 20.6.0
    installed: false
    hooks:
      - events: [ "postsync" ]
        showlogs: true
        command: "kubectl"
        args: [ "apply", "-k", "kustomize/overlays/{{`{{ .Environment.Name }}`}}" ]
    values:
      - metrics:
          enabled: true
