apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopware
resources:
  - deployment.yaml
  - configmap.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - cronjob.yaml
