apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopware-docroot
  namespace: shopware
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
