services:
  traefik:
    image: traefik:v3.0.4
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public
    labels:
      - "application=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.tls.domains[0].main=traefik.shopware.internal"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.traefik.shopware.internal"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.shopware.internal`)"
    configs:
      - source: traefik.yml
        target: /etc/traefik/traefik.yml
      - source: traefik-dynamic.yml
        target: /etc/traefik/traefik-dynamic.yml
    secrets:
      - source: server.pem
        target: /etc/ssl/traefik/server.pem
      - source: server-key.pem
        target: /etc/ssl/traefik/server-key.pem
    security_opt:
      - no-new-privileges:true

  shopware:
    image: fmjstudios/shopware:latest
    container_name: shopware
    env_file: .env.local
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - "9161"
    volumes:
      - sw-files:/var/www/html/files:rw
      - sw-theme:/var/www/html/public/theme:rw
      - sw-media:/var/www/html/public/media:rw
      - sw-thumbnail:/var/www/html/public/thumbnail:rw
      - sw-sitemap:/var/www/html/public/sitemap:rw
    networks:
      - public
      - internal
    labels:
      - "application=shopware"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.shopware.entrypoints=https"
      - "traefik.http.routers.shopware.tls=true"
      - "traefik.http.routers.shopware.tls.domains[0].main=shopware.internal"
      #- "traefik.http.routers.shopware.tls.domains[0].sans=*.shopware.internal"
      - "traefik.http.routers.shopware.rule=Host(`shopware.internal`)"
      - "traefik.http.routers.shopware.service=shopware"
      - "traefik.http.services.shopware.loadbalancer.server.port=9161"
      - "traefik.http.services.shopware.loadbalancer.sticky=true"
      - "traefik.http.services.shopware.loadbalancer.sticky.cookie=true"
    healthcheck:
      test: [ "CMD", "curl" ,"--fail", "http://localhost:9161/api/_info/health-check" ]
      start_period: 3m
      interval: 1m
      timeout: 5s
      retries: 10
    depends_on:
      traefik:
        condition: service_started
      mysql:
        condition: service_started
      opensearch:
        condition: service_started
      mailpit:
        condition: service_started

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}-oracle
    container_name: mysql
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shopware}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-shopware}
      MYSQL_USER: ${MYSQL_USER:-shopware}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-shopware}
    volumes:
      - db-data:/var/lib/mysql:rw
      - ./docker/conf/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
    labels:
      - "application=mysql"
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-shopware}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  # ref: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    ports:
      - "9200" # REST API
      - "9600" # Performance Analyzer
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "AShopware6Password!"
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - internal
    labels:
      - "application=opensearch"
      - "traefik.enable=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  # ref: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    ports:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      opensearch.username: shopware
      opensearch.password: shopware
    networks:
      - public
      - internal # needs opensearch access
    labels:
      - "application=opensearch-dashboards"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.opensearch.entrypoints=https"
      - "traefik.http.routers.opensearch.tls=true"
      - "traefik.http.routers.opensearch.tls.domains[0].main=opensearch.shopware.internal"
      - "traefik.http.routers.opensearch.tls.domains[0].sans=*.opensearch.shopware.internal"
      - "traefik.http.routers.opensearch.rule=Host(`opensearch.shopware.internal`)"
      - "traefik.http.routers.opensearch.service=opensearch"
      - "traefik.http.services.opensearch.loadbalancer.server.port=5601"

  # ref: https://mailpit.axllent.org/docs/configuration/runtime-options/
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - public
    labels:
      - "application=mailpit"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.mailpit.entrypoints=https"
      - "traefik.http.routers.mailpit.tls=true"
      - "traefik.http.routers.mailpit.tls.domains[0].main=mailpit.shopware.internal"
      - "traefik.http.routers.mailpit.tls.domains[0].sans=*.mailpit.shopware.internal"
      - "traefik.http.routers.mailpit.rule=Host(`mailpit.shopware.internal`)"
      - "traefik.http.routers.mailpit.service=mailpit"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"

  # ref: https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    ports:
      - "8090"
    environment:
      APACHE_PORT: 8090
      MYSQL_ROOT_PASSWORD: shopware
      PMA_HOST: mysql
      # PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: https://phpmyadmin.shopware.internal
    networks:
      - public
      - internal # needs mysql access
    labels:
      - "application=phpmyadmin"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.phpmyadmin.entrypoints=https"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.domains[0].main=phpmyadmin.shopware.internal"
      - "traefik.http.routers.phpmyadmin.tls.domains[0].sans=*.phpmyadmin.shopware.internal"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.shopware.internal`)"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=8090"

  # ref: https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/docker-compose.yaml
  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000"
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: grafana-opensearch-datasource
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
      GF_SERVER_ROOT_URL: "https://grafana.shopware.internal"
    networks:
      - public
      - internal # tempo, otel-c access
    configs:
      - source: grafana-datasources.yaml
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    labels:
      - "application=grafana"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.domains[0].main=grafana.shopware.internal"
      - "traefik.http.routers.grafana.tls.domains[0].sans=*.grafana.shopware.internal"
      - "traefik.http.routers.grafana.rule=Host(`grafana.shopware.internal`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  tempo-init:
    image: grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo-data:/var/tempo

  # ref: https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/docker-compose.yaml
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo-data:/var/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    configs:
      - source: tempo.yaml
        target: /etc/tempo.yaml
    networks:
      - internal
    depends_on:
      - tempo-init
    labels:
      - "application=tempo"
      - "traefik.enable=false"

  # ref: https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/docker-compose.yaml
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    configs:
      - source: prometheus.yaml
        target: /etc/prometheus.yaml
    ports:
      - "9090"
    networks:
      - public
      - internal # otel-c access
    labels:
      - "application=prometheus"
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.domains[0].main=prometheus.shopware.internal"
      - "traefik.http.routers.prometheus.tls.domains[0].sans=*.prometheus.shopware.internal"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.shopware.internal`)"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  # ref: https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/docker-compose.yaml
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.110.0
    container_name: otel-collector
    restart: always
    command: [ "--config=/etc/otel-collector.yaml" ]
    configs:
      - source: otel-collector-config.yaml
        target: /etc/otel-collector.yaml
    ports:
      - "4317" # OTLP gRPC receiver
    networks:
      - internal
    depends_on:
      - grafana
      - tempo
    labels:
      - "application=otel-collector"
      - "traefik.enable=false"

configs:
  traefik.yml:
    file: docker/resources/traefik.yml
  traefik-dynamic.yml:
    file: docker/resources/traefik-dynamic.yml
  grafana-datasources.yaml:
    file: docker/resources/grafana-datasources.yaml
  tempo.yaml:
    file: docker/resources/tempo.yaml
  prometheus.yaml:
    file: docker/resources/prometheus.yaml
  otel-collector-config.yaml:
    file: docker/resources/otel-collector-config.yaml

secrets:
  server.pem:
    file: secrets/ssl/server.pem
  server-key.pem:
    file: secrets/ssl/server-key.pem

volumes:
  sw-files:
  sw-theme:
  sw-media:
  sw-thumbnail:
  sw-sitemap:
  db-data:
  opensearch-data:
  tempo-data:

networks:
  public:
    external: true
  internal:
