version: '3'

services:

  shopware:
    image: local
    build:
      context: ..
      dockerfile: Dockerfile.nginx
    env_file: ../.app.env
    ports:
      - "8000"
    volumes:
      - files:/var/www/html/files
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - sitemap:/var/www/html/public/sitemap
    networks:
      - web
      - internal

  database:
    image: mysql:${MYSQL_VERSION:-8}-oracle
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shopware}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-shopware}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - internal

  opensearch:
    image: opensearchproject/opensearch:2
    ports:
      - "9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'
    networks:
      - internal

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - internal

volumes:
  db-data:
  opensearch-data:

networks:
  web:
  internal: