---
{{- $repoDir := exec "git" (list "rev-parse" "--show-toplevel") | trim }}
{{- $envDir := (print $repoDir "/deploy/env") }}
{{- $appDir := (print $repoDir "/deploy/app") }}

helmDefaults:
  atomic: true
  cleanupOnFail: true
  # this has to be 'false' since kube-prometheus-stack doesn't provide provenance files, so verification will always fail
  verify: false
  wait: true
  waitForJobs: true
  recreatePods: false
  createNamespace: true

helmfiles:
  - {{ $appDir }}/helmfile.yaml

releases:
  # ref: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  - chart: ingress-nginx/ingress-nginx
    name: ingress-nginx
    namespace: ingress-nginx
    version: 4.11.3
    installed: true
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/ingress-nginx.yaml

  # ref: https://artifacthub.io/packages/helm/cert-manager/cert-manager
  - chart: jetstack/cert-manager
    name: cert-manager
    namespace: cert-manager
    version: 1.16.2
    installed: true
    hooks:
      - events: [ "postsync" ]
        showlogs: true
        command: "kubectl"
        args: [ "apply", "-k", "kustomize" ]
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/cert-manager.yaml

  # ref: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
  - chart: opentelemetry/kube-prometheus-stack
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
    version: 67.2.0
    installed: true
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/kube-prometheus-stack.yaml

  # ref: https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator
  - chart: opentelemetry/opentelemetry-operator
    name: opentelemetry-operator
    namespace: opentelemetry-operator
    version: 0.75.1
    installed: true
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/opentelemetry-operator.yaml

  # ref: https://artifacthub.io/packages/helm/elastic/eck-operator
  - chart: elastic/eck-operator
    name: eck-operator
    namespace: eck-operator
    version: 2.15.0
    installed: true
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/eck-operator.yaml

  # ref: https://github.com/percona/percona-helm-charts/tree/main/charts/pxc-operator
  - chart: percona/pxc-operator
    name: pxc-operator
    namespace: pxc-operator
    version: 1.15.1
    installed: true
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/pxc-operator.yaml
