---
{{- $repoDir := exec "git" (list "rev-parse" "--show-toplevel") | trim }}
{{- $envDir := (print $repoDir "/deploy/env") }}
{{- $appDir := (print $repoDir "/deploy/app") }}

helmDefaults:
  atomic: true
  cleanupOnFail: true
  # this has to be 'false' since kube-prometheus-stack doesn't provide provenance files, so verification will always fail
  verify: false
  wait: true
  waitForJobs: true
  recreatePods: false
  createNamespace: true

bases:
  - {{ $envDir }}/repositories.yaml
  - {{ $envDir }}/environments.yaml

helmfiles:
  - {{ $appDir }}/helmfile.yaml

releases:
  # ref: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  - chart: ingress-nginx/ingress-nginx
    name: ingress-nginx
    namespace: ingress-nginx
    version: 4.11.3
    installed: true
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/ingress-nginx.yaml

  # ref: https://artifacthub.io/packages/helm/cert-manager/cert-manager
  - chart: jetstack/cert-manager
    name: cert-manager
    namespace: cert-manager
    version: 1.16.2
    installed: true
    disableValidationOnInstall: true
    hooks:
      - events: [ "postsync" ]
        showlogs: true
        command: "kubectl"
        args: [ "apply", "-k", "kustomize/overlays/{{`{{ .Environment.Name }}`}}" ]
    labels:
      release: cert-manager
    needs:
      - ingress-nginx/ingress-nginx
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/cert-manager.yaml

  # ref: https://artifacthub.io/packages/helm/bitnami/external-dns
  - chart: bitnami/external-dns
    name: external-dns
    namespace: external-dns
    version: 8.7.0
    {{- if eq .Environment.Name "dev" }}
    installed: false
    {{ else }}
    installed: true
    {{- end }}
    disableValidationOnInstall: true
    labels:
      release: external-dns
    needs:
      - ingress-nginx/ingress-nginx
      - cert-manager/cert-manager
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/external-dns.yaml

  # ref: https://artifacthub.io/packages/helm/metrics-server/metrics-server
  - chart: metrics-server/metrics-server
    name: metrics-server
    namespace: metrics-server
    version: 3.12.2
    installed: true
    disableValidationOnInstall: true
    labels:
      release: metrics-server
    needs:
      - ingress-nginx/ingress-nginx
      - cert-manager/cert-manager
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/metrics-server.yaml

  # ref: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
  - chart: prometheus-community/kube-prometheus-stack
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
    version: 67.2.0
    installed: true
    disableValidationOnInstall: true
    labels:
      release: kube-prometheus-stack
    needs:
      - ingress-nginx/ingress-nginx
      - cert-manager/cert-manager
      - metrics-server/metrics-server
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/kube-prometheus-stack.yaml

  # ref: https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator
  - chart: opentelemetry/opentelemetry-operator
    name: opentelemetry-operator
    namespace: opentelemetry-operator
    version: 0.75.1
    installed: true
    disableValidationOnInstall: true
    labels:
      release: opentelemetry-operator
    needs:
      - cert-manager/cert-manager
      - kube-prometheus-stack/kube-prometheus-stack
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/opentelemetry-operator.yaml

  # ref: https://artifacthub.io/packages/helm/elastic/eck-operator
  - chart: elastic/eck-operator
    name: eck-operator
    namespace: eck-operator
    version: 2.15.0
    installed: false
    disableValidationOnInstall: true
    labels:
      release: eck-operator
    needs:
      - cert-manager/cert-manager
      - kube-prometheus-stack/kube-prometheus-stack
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/eck-operator.yaml

  # ref: https://github.com/opensearch-project/opensearch-k8s-operator/tree/main/charts/opensearch-operator
  - chart: opensearch-operator/opensearch-operator
    name: opensearch-operator
    namespace: opensearch-operator
    version: 2.7.0
    installed: true
    disableValidationOnInstall: true
    labels:
      release: opensearch-operator
    needs:
      - cert-manager/cert-manager
      - kube-prometheus-stack/kube-prometheus-stack
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/opensearch-operator.yaml

  # ref: https://github.com/percona/percona-helm-charts/tree/main/charts/pxc-operator
  - chart: percona/pxc-operator
    name: pxc-operator
    namespace: pxc-operator
    version: 1.15.1
    installed: true
    disableValidationOnInstall: true
    labels:
      release: pxc-operator
    needs:
      - cert-manager/cert-manager
      - kube-prometheus-stack/kube-prometheus-stack
    values:
      - {{ $envDir }}/{{`{{ .Environment.Name }}`}}/pxc-operator.yaml
