# Using the web-updater would overwrite this file, requiring a second file z-shopware.yaml to override the config
# We toggled the updater with `shopware.auto_update.enabled = false`

shopware:
  # S3 configuration
  #
  # Public files: product images, thumbnails, category images, etc.
  filesystem:
    public:
      url: "%env(S3_CDN_URL)%"
      type: "amazon-s3"
      visibility: "public"
      config:
        bucket: "%env(S3_PUBLIC_BUCKET)%"
        region: "%env(S3_REGION)%"
        endpoint: "%env(S3_ENDPOINT)%"
        use_path_style_endpoint: "%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%"
        options:
          visibility: "public"
          credentials:
            key: "%env(S3_ACCESS_KEY)%"
            secret: "%env(S3_SECRET_KEY)%"

    # Private files: invoices, delivery notes, etc.
    # NOTE: omit URL here, since they shouldn't be publicly accessible
    private:
      type: "amazon-s3"
      visibility: "private"
      config:
        bucket: "%env(S3_PRIVATE_BUCKET)%"
        region: "%env(S3_REGION)%"
        endpoint: "%env(S3_ENDPOINT)%"
        use_path_style_endpoint: "%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%"
        options:
          visibility: "private"
          credentials:
            key: "%env(S3_ACCESS_KEY)%"
            secret: "%env(S3_SECRET_KEY)%"

    # Theme configuration
    theme:
      url: "%env(S3_CDN_URL)%"
      type: "amazon-s3"
      config:
        bucket: "%env(S3_PUBLIC_BUCKET)%"
        region: "%env(S3_REGION)%"
        endpoint: "%env(S3_ENDPOINT)%"
        use_path_style_endpoint: "%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%"
        options:
          credentials:
            key: "%env(S3_ACCESS_KEY)%"
            secret: "%env(S3_SECRET_KEY)%"
    asset:
      url: "%env(S3_CDN_URL)%"
      type: "amazon-s3"
      config:
        bucket: "%env(S3_PUBLIC_BUCKET)%"
        region: "%env(S3_REGION)%"
        endpoint: "%env(S3_ENDPOINT)%"
        use_path_style_endpoint: "%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%"
        options:
          credentials:
            key: "%env(S3_ACCESS_KEY)%"
            secret: "%env(S3_SECRET_KEY)%"
    sitemap:
      url: "%env(S3_CDN_URL)%"
      type: "amazon-s3"
      config:
        bucket: "%env(S3_PUBLIC_BUCKET)%"
        region: "%env(S3_REGION)%"
        endpoint: "%env(S3_ENDPOINT)%"
        use_path_style_endpoint: "%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%"
        options:
          credentials:
            key: "%env(S3_ACCESS_KEY)%"
            secret: "%env(S3_SECRET_KEY)%"

  # Redis Configuration
  # ref: https://developer.shopware.com/docs/guides/hosting/infrastructure/redis.html
  redis:
    connections:
      # db 0 are PHP sessions
      ephemeral:
        dsn: "%env(REDIS_URL)%/1"
      persistent:
        dsn: "%env(REDIS_URL)%/2?persistent=1"

  # ref: https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks.html#using-zstd-instead-of-gzip-for-compression
  cart:
    compress: true
    compression_method: zstd
    # use Redis for cart storage (see tab 'Since 6.6.8.0')
    # ref: https://developer.shopware.com/docs/guides/hosting/performance/cart-storage.html
    storage:
      type: redis
      config:
        connection: persistent

  cache:
    cache_compression: true
    cache_compression_method: zstd

  api:
    # Configure rate-limiting for all admin-facing endpoints
    rate_limiter:
      # Storefront (customer-facing) endpoints
      login:
        enabled: false
      guest_login:
        enabled: false
      reset_password:
        enabled: false
      contact_form:
        enabled: false
      # API/Administration logins
      oauth:
        enabled: true
        policy: "time_backoff"
        reset: "24 hours"
        limits:
          - limit: 5
            interval: "10 seconds"
          - limit: 10
            interval: "60 seconds"
      # Administration user password recovery
      user_recovery:
        enabled: true
        policy: "time_backoff"
        reset: "24 hours"
        limits:
          - limit: 3
            interval: "10 seconds"
          - limit: 5
            interval: "60 seconds"
