apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    fmj.studio/component: cert-manager
    fmj.studio/env: dev
  name: development-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-ca
