# ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

#extensions:
#  health_check:
#  pprof:
#    endpoint: :1888
#  zpages:
#    endpoint: :55679

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
#    metrics:
#      receivers: [ otlp ]
#      processors: [ batch ]
#      exporters: [ debug, prometheus ]
