version: '3.7'

services:
  database:
    image: mysql:${MYSQL_VERSION:-8}-oracle
    ports:
      - '3306:3306'
    tmpfs:
      - /var/lib/mysql:uid=999,gid=999
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shopware}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-shopware}
      MYSQL_USER: ${MYSQL_USER:-shopware}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-shopware}

  mailer:
    image: mailhog/mailhog
    ports:
      - '8025:8025'

  opensearch:
    image: opensearchproject/opensearch:2
    ports:
      - '9200:9200'
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'

volumes:
  db-data:
  opensearch-data: