apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - namespace.yaml
  - serviceaccount.yaml
  # CRDs
  - opensearch.yaml
  - percona-mysql.yaml
