apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: shopware-mysql
  namespace: shopware
spec:
  secretsName: shopware-db-credentials
  crVersion: 1.14.1
  allowUnsafeConfigurations: true
  initImage: "percona/percona-xtradb-cluster-operator:1.14.1"
  pxc:
    size: 1
    image: percona/percona-xtradb-cluster:8.0
    autoRecovery: true
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: ""
        resources:
          requests:
            storage: 8Gi
    gracePeriod: 600

    # https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks.html
    configuration: |
      [mysqld]
      group_concat_max_len=320000
      sql_mode=''

  proxysql:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.14.1-proxysql
    size: 1
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: ""
        resources:
          requests:
            storage: "10G"
