global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  https:
    address: ":443"
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

providers:
  file:
    filename: /etc/traefik/traefik-dynamic.yml
    watch: true
  docker:
    defaultRule: Host(`shopware.internal`)
    exposedByDefault: false
    network: public
    watch: true
    endpoint: unix:///var/run/docker.sock

serversTransport:
  insecureSkipVerify: true

log:
  filePath: /var/log/traefik/traefik.log
  format: common
  level: DEBUG

api:
  insecure: false
  dashboard: true

accessLog:
  filePath: /var/log/traefik/access.log
  format: json
#  filters:
#    statusCodes:
#      - "200"
#      - "300-302"
#    retryAttempts: true
#    minDuration: "10s"
