#!/bin/bash
#
# Copyright Ad Noctem Collective. All Rights Reserved.
# SPDX-License-Idenifier: MIT
#
# Build the Shopware 6 environment variables to be loaded ahead of starting the main,
# to avoid cluttering the entire container with (default) environment variables.

# General settings
export APP_ENV=${APP_ENV:-"dev"}
export APP_SECRET=${APP_SECRET:-""}
export APP_URL=${APP_URL:-"http://localhost:8000"}
export APP_URL_CHECK_DISABLED=${APP_URL_CHECK_DISABLED:-"0"}
export INSTANCE_ID=${INSTANCE_ID:-""}
export BLUE_GREEN_DEPLOYMENT=${BLUE_GREEN_DEPLOYMENT:-"0"}
export SHOPWARE_CACHE_ID=${SHOPWARE_CACHE_ID:-"sw"}
export SHOPWARE_SKIP_WEBINSTALLER=${SHOPWARE_SKIP_WEBINSTALLER:-"1"}
export SQL_SET_DEFAULT_SESSION_VARIABLES=${SQL_SET_DEFAULT_SESSION_VARIABLES:-"1"}
export LOCK_DSN=${LOCK_DSN:-"flock"}

# MySQL
DATABASE_PROTOCOL=${DATABASE_PROTOCOL:-"mysql"}
DATABASE_USER=${DATABASE_USER:-"shopware"}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-"shopware"}
DATABASE_HOST=${DATABASE_HOST:-"mysql"}
DATABASE_PORT=${DATABASE_PORT:-"3306"}
DATABASE_NAME=${DATABASE_NAME:-"shopware"}
export DATABASE_URL=${DATABASE_URL:-"${DATABASE_PROTOCOL}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"}
unset DATABASE_PROTOCOL DATABASE_USER DATABASE_PASSWORD DATABASE_HOST DATABASE_PORT DATABASE_NAME

# Redis
REDIS_PROTOCOL=${REDIS_PROTOCOL:-"redis"}
REDIS_USER=${REDIS_USER:-""}
REDIS_PASSWORD=${REDIS_PASSWORD:-""}
REDIS_HOST=${REDIS_HOST:-"redis"}
REDIS_PORT=${REDIS_PORT:-"6379"}
# handle possible Redis ACL configuration
if [[ "${REDIS_USER}" != "" ]]; then
  export REDIS_URL=${REDIS_URL:-"${REDIS_PROTOCOL}://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"}
else
  export REDIS_URL=${REDIS_URL:-"${REDIS_PROTOCOL}://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"}
fi
unset REDIS_PROTOCOL REDIS_USER REDIS_PASSWORD REDIS_HOST REDIS_PORT

# Messenger
MESSENGER_PROTOCOL=${MESSENGER_PROTOCOL:-"amqp"}
MESSENGER_USER=${MESSENGER_USER:-"shopware"}
MESSENGER_PASSWORD=${MESSENGER_PASSWORD:-"shopware"}
MESSENGER_HOST=${MESSENGER_HOST:-"rabbitmq"}
MESSENGER_PORT=${MESSENGER_PORT:-"5672"}
MESSENGER_PATH=${MESSENGER_PATH:-"/%2f/async"}
MESSENGER_QUERY_PARAMS=${MESSENGER_QUERY_PARAMS:-"?auto_setup=false"}
MESSENGER_TRANSPORT_LOW_PRIORITY_PATH=${MESSENGER_TRANSPORT_LOW_PRIORITY_PATH:-"/%2f/low_priority"}
MESSENGER_TRANSPORT_LOW_PRIORITY_QUERY_PARAMS=${MESSENGER_TRANSPORT_LOW_PRIORITY_QUERY_PARAMS:-"?auto_setup=false"}
MESSENGER_TRANSPORT_FAILURE_PATH=${MESSENGER_TRANSPORT_FAILURE_PATH:-"/%2f/failed"}
MESSENGER_TRANSPORT_FAILURE_QUERY_PARAMS=${MESSENGER_TRANSPORT_FAILURE_QUERY_PARAMS:-"?auto_setup=false"}
export MESSENGER_TRANSPORT_DSN="${MESSENGER_TRANSPORT_DSN:-"${MESSENGER_PROTOCOL}://${MESSENGER_USER}:${MESSENGER_PASSWORD}@${MESSENGER_HOST}:${MESSENGER_PORT}${MESSENGER_PATH}${MESSENGER_QUERY_PARAMS}"}"
export MESSENGER_TRANSPORT_LOW_PRIORITY_DSN="${MESSENGER_TRANSPORT_DSN:-"${MESSENGER_PROTOCOL}://${MESSENGER_USER}:${MESSENGER_PASSWORD}@${MESSENGER_HOST}:${MESSENGER_PORT}${MESSENGER_TRANSPORT_LOW_PRIORITY_PATH}${MESSENGER_TRANSPORT_LOW_PRIORITY_QUERY_PARAMS}"}"
export MESSENGER_TRANSPORT_FAILURE_DSN="${MESSENGER_TRANSPORT_DSN:-"${MESSENGER_PROTOCOL}://${MESSENGER_USER}:${MESSENGER_PASSWORD}@${MESSENGER_HOST}:${MESSENGER_PORT}${MESSENGER_TRANSPORT_FAILURE_PATH}${MESSENGER_TRANSPORT_FAILURE_QUERY_PARAMS}"}"
unset MESSENGER_PROTOCOL MESSENGER_USER MESSENGER_PASSWORD MESSENGER_HOST MESSENGER_PORT MESSENGER_PATH MESSENGER_QUERY_PARAMS MESSENGER_TRANSPORT_LOW_PRIORITY_PATH MESSENGER_TRANSPORT_LOW_PRIORITY_QUERY_PARAMS MESSENGER_TRANSPORT_FAILURE_PATH MESSENGER_TRANSPORT_FAILURE_QUERY_PARAMS

# OpenSearch
OPENSEARCH_PROTOCOL=${OPENSEARCH_PROTOCOL:-"http"}
OPENSEARCH_USER=${OPENSEARCH_USER:-""}
OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD:-""}
OPENSEARCH_HOST=${OPENSEARCH_HOST:-"opensearch"}
OPENSEARCH_PORT=${OPENSEARCH_PORT:-"9200"}
export OPENSEARCH_URL=${OPENSEARCH_URL:-"${OPENSEARCH_PROTOCOL}://${OPENSEARCH_USER}:${OPENSEARCH_PASSWORD}@${OPENSEARCH_HOST}:${OPENSEARCH_PORT}"}
unset OPENSEARCH_PROTOCOL OPENSEARCH_USER OPENSEARCH_PASSWORD OPENSEARCH_HOST OPENSEARCH_PORT

# SMTP
MAILER_PROTOCOL=${MAILER_PROTOCOL:-"smtp"}
MAILER_USER=${MAILER_USER:-"null"}
MAILER_PASSWORD=${MAILER_PASSWORD:-"null"}
MAILER_HOST=${MAILER_HOST:-"null"}
MAILER_PORT=${MAILER_PORT:-"1025"}
export MAILER_DSN=${MAILER_DSN:-"${MAILER_PROTOCOL}://${MAILER_USER}:${MAILER_PASSWORD}@${MAILER_HOST}:${MAILER_PORT}"}
unset MAILER_PROTOCOL MAILER_USER MAILER_PASSWORD MAILER_HOST MAILER_PORT

# HTTP caching settings (disabled by default)
export SHOPWARE_HTTP_CACHE_ENABLED=${SHOPWARE_HTTP_CACHE_ENABLED:-"0"}
export SHOPWARE_HTTP_DEFAULT_TTL=${SHOPWARE_HTTP_DEFAULT_TTL:-"7200"}
export STOREFRONT_PROXY_URL=${STOREFRONT_PROXY_URL:-"${APP_URL}"}

# disable ElasticSearch/OpenSearch by default
export SHOPWARE_ES_ENABLED=${SHOPWARE_ES_ENABLED:-"0"}
export SHOPWARE_ES_INDEXING_ENABLED=${SHOPWARE_ES_INDEXING_ENABLED:-"0"}
export SHOPWARE_ES_INDEX_PREFIX=${SHOPWARE_ES_INDEX_PREFIX:-"sw"}
export SHOPWARE_ES_THROW_EXCEPTION=${SHOPWARE_ES_THROW_EXCEPTION:-"1"}

# disable OpenTelemetry by default
export OTEL_PHP_AUTOLOAD_ENABLED=${OTEL_PHP_AUTOLOAD_ENABLED:-"false"}
export OTEL_PHP_DISABLED_INSTRUMENTATIONS=${OTEL_PHP_DISABLED_INSTRUMENTATIONS:-"shopware"}
export OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-"shopware"}
export OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER:-"otlp"}
export OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER:-"otlp"}
export OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER:-"otlp"}
export OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL:-"grpc"}
export OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-"https://otel-collector:4317"}

# S3 configuration
export S3_PUBLIC_BUCKET=${S3_PUBLIC_BUCKET:-"shop-public"}
export S3_PRIVATE_BUCKET=${S3_PRIVATE_BUCKET:-"shop-private"}
export S3_REGION=${S3_REGION:-"eu-north-1"}
export S3_ACCESS_KEY=${S3_ACCESS_KEY:-"CHANGEME"}
export S3_SECRET_KEY=${S3_SECRET_KEY:-"CHANGEME"}
# fix invalid S3 credential issue due to a bug in Shopware's filesystem abstraction
# ref: https://github.com/thephpleague/flysystem/issues/1759
export AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY:-"CHANGEME"}
export AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY:-"CHANGEME"}
export S3_ENDPOINT=${S3_ENDPOINT:-"https://s3.eu-north-1.amazonaws.com"}
export S3_CDN_URL=${S3_CDN_URL:-"https://shop.cdn.fmj.services"}
export S3_USE_PATH_STYLE_ENDPOINT=${S3_USE_PATH_STYLE_ENDPOINT:-"false"}

# Shopware Deployment Helper (or our installation script)
export INSTALL_LOCALE=${INSTALL_LOCALE:-"de-DE"}
export INSTALL_CURRENCY=${INSTALL_CURRENCY:-"EUR"}
export INSTALL_ADMIN_USERNAME=${INSTALL_ADMIN_USERNAME:-"admin"}
export INSTALL_ADMIN_PASSWORD=${INSTALL_ADMIN_PASSWORD:-"shopware"}
export SALES_CHANNEL_NAME=${SALES_CHANNEL_NAME:-"Storefront"}
export SALES_CHANNEL_URL=${SALES_CHANNEL_URL:-"${APP_URL}"}
export SALES_CHANNEL_THEME=${SALES_CHANNEL_THEME:-"Storefront"}
