name: 'Release'

permissions: read-all

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  info:
    name: Determine package info
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.output-version.outputs.version }}
      name: ${{ steps.output-name.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Output version
        id: output-version
        run: |
          VERSION=$(make version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Output name
        id: output-name
        run: |
          NAME=$(make name)
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    needs: [ 'info' ]
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/'${{ needs.info.outputs.name }}'
          tags: |
            type=semver,prefix=v,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}