name: 'Test Shopware 6'

permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - custom/**
  pull_request:
    branches:
      - main
      - release
    paths:
      - custom/**

defaults:
  run:
    shell: bash



jobs:
  generate-matrix:
    name: "Generate a Matrix"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Matrix
        id: gen-matrix
        run: |
          MATRIX=$(php scripts/ci/matrix.php)
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$MATRIX" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    needs: [ 'generate-matrix' ]
    permissions:
      contents: read
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          shopware-version: 'trunk'
          php-version: ${{ matrix.php_version }}
          php-extensions: pcov

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            custom

      - name: Install Extension with Composer
        run: |
          composer require $(composer -d custom/plugins/${{ matrix.plugin }} config name)

      - name: Run PHPUnit
        working-directory: ${{ github.workspace }}/custom/plugins/${{ matrix.plugins }}
        run: |
          ${{ github.workspace }}/vendor/bin/phpunit --coverage-clover clover.xml

      - name:

          

